title: Greg Frazier
description: A place for my stuff. 

url: https://gnfrazier.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
# - title: About
 #  url: /about
 #- title: Contact
 #  url: /contact

social:
   github: gnfrazier
   twitter: gnfrazier
   # facebook: 
   # email: 

google_analytics: "UA-112501792-2"
